name: .NET Framework Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build project
      run: msbuild HDT-Reconnector.sln /p:Configuration=Release

    - name: Run tests (if any)
      run: |
        vstest.console.exe "**\*.Test.dll" /TestCaseFilter:"TestCategory!=Integration" --logger:trx
